### ISSUE TITLE
🎨  UI Design Palette Color

### ISSUE THREAD

**Issue by an-jorge** [epifaniofrancisco/verificador-de-bi#2]
Boas,
Uma melhoria na UI seria bem-vindo, uma vez que objetivo principal da aplicação é a verificação do BI.
Teria mais sentido se a identidade visual fosse igual a do BI, me referi a combinação de cores principalmente.

Parabéns pelo iniciativa ❤️ .

**Comment by epifaniofrancisco** [comment]
Era isso que estava a tentar fazer, mas não consigo encontrar as cores presentes no BI.

Se poderes ajudar com a paleta de cores agradeceria.

**Comment by an-jorge** [comment]
Vou contribuir no projecto

**Comment by epifaniofrancisco** [comment]
Espero que sim.

Se conseguires encontrar as cores do BI, ou algumas que se aproximam a elas, envia❤️

**Comment by an-jorge** [comment]
Não gostei da Palette com as cores originais do B.I.
Dê uma olhada na abaixo.

#EECB64 - Castanho
#F6D268 - Amarelo
#FFFFFF - Branco
#000000 - Preto

@epifaniofrancisco 
Faltou a cor vermelha mais na interface pode ser colocado de um jeito inteligente

![Palette-2](https://user-images.githubusercontent.com/10496881/168122040-a46c52fc-2625-400d-b6a9-2866095c544e.PNG)
