### ISSUE TITLE
🥷 Gostei do projeto, fiquei a saber dessa API do Governo.

### ISSUE THREAD

**Issue by Vivaldo-Roque** [epifaniofrancisco/verificador-de-bi#3]
https://api.gov.ao/consultarBI/v2/?bi="SEU_BI"

**Comment by epifaniofrancisco** [comment]
É uma API boa, mas infelizmente não fornece todos os dados.

**Comment by an-jorge** [comment]
Qual é a API que estás a utilizar ?
@epifaniofrancisco 

Onde encontraste está API ?
@Vivaldo-Roque

**Comment by Vivaldo-Roque** [comment]
@an-jorge achei a API lendo o projeto do @epifaniofrancisco.

**Comment by Vivaldo-Roque** [comment]
> É uma API boa, mas infelizmente não fornece todos os dados.

Concordo tinha que retornar foto.

**Comment by an-jorge** [comment]
@Vivaldo-Roque agora que você falou encontrei algo parecido no projecto, achei que estivesses a se referir a uma API diferente com o mesmo objectivo.

**Comment by Vivaldo-Roque** [comment]
> @Vivaldo-Roque agora que você falou encontrei algo parecido no projecto, achei que estivesses a se referir a uma API diferente com o mesmo objectivo.

😅 Desculpa se causei alguma confusão.

**Comment by an-jorge** [comment]
Está tranquilo @Vivaldo-Roque  
Nunca temos um pronunciamento clara do nosso estado, não dizem sobre as API disponíveis ou quando disponibilizam tudo é um tiro no escuro.
Gostaria de saber do @epifaniofrancisco onde encontrou a API
